// AUTO-GENERATED FROM ssid_list.conf - DO NOT EDIT DIRECTLY
#pragma once

static const char EMBEDDED_SSID_LIST_CONF[] =
    "# ============================================================\n"
    "# PhantomProbe-C6: Wireless RF Security Research & Telemetry Probe\n"
    "# Target Hardware: ESP32-C6-DevKitC-1 (Wi-Fi 6 / BLE 5 / IEEE 802.15.4)\n"
    "# ============================================================\n"
    "# Declarative deployment manifest for multi-BSSID environment simulation,\n"
    "# wireless honeypot probing, and BLE accessory reconnaissance research.\n"
    "# Apply changes instantly with: .\\flash_firmware.ps1\n"
    "\n"
    "[wifi]\n"
    "# Target 2.4 GHz RF Channel (1 to 13)\n"
    "channel = 1\n"
    "\n"
    "# Delay between beacon injection cycles in milliseconds (Default: 50 ms)\n"
    "# Fast injection rates (30-50ms) ensure rapid detection by client WNICs.\n"
    "burst_interval_ms = 50\n"
    "\n"
    "# Inter-frame gap between consecutive virtual beacons within a burst (Default: 2 ms)\n"
    "burst_gap_ms = 2\n"
    "\n"
    "# Active Probe Responder: Replies to 802.11 Probe Requests (1 = enabled, 0 = disabled)\n"
    "enable_probe_responder = 1\n"
    "\n"
    "[networks]\n"
    "# Synthetic targets / honeypot virtual SSIDs (one per line, max 32 characters each)\n"
    "# Each SSID automatically receives a unique locally-administered BSSID.\n"
    "IoT-Sensors-Net\n"
    "IoT-Cameras-Net\n"
    "IoT-Automation-Net\n"
    "IoT-Isolated-DMZ\n"
    "IoT-Guest-Net\n"
    "\n"
    "[bluetooth]\n"
    "# Enable Bluetooth multi-identity advertising (1 = enabled, 0 = disabled)\n"
    "enable_ble = 1\n"
    "\n"
    "# Bluetooth advertisement dwell / rotation interval in milliseconds (Default: 2000 ms)\n"
    "# Each interval, the board switches to the next virtual Bluetooth identity.\n"
    "# Note: Phones (iOS/Android) scan periodically across RF channels and require\n"
    "# at least 1500 - 2500 ms dwell time per identity to discover and list all devices.\n"
    "ble_adv_interval_ms = 2000\n"
    "\n"
    "# Native OS Bluetooth discovery accessory emulation:\n"
    "# Standard phone/laptop Bluetooth settings screens ignore generic beacons and only\n"
    "# display accessories/peripherals. Select which accessory type to emulate:\n"
    "#   0  = Generic BLE device (Device Information Service 0x180A)\n"
    "#   1  = Keyboard (HID 0x03C1, Service 0x1812) - Keyboard icon\n"
    "#   2  = Mouse (HID 0x03C2, Service 0x1812) - Mouse icon\n"
    "#   3  = Gamepad / Controller (HID 0x03C4, Service 0x1812) - Controller icon\n"
    "#   4  = Joystick (HID 0x03C3, Service 0x1812) - Joystick icon\n"
    "#   5  = Remote Control (HID 0x03C8, Service 0x1812) - Remote icon\n"
    "#   6  = Smartwatch (Appearance 0x00C2, Service 0x1805) - Watch icon\n"
    "#   7  = Heart Rate Monitor (Appearance 0x0341, Service 0x180D) - Heart Rate icon\n"
    "#   8  = Health Thermometer (Appearance 0x0300, Service 0x1809) - Thermometer icon\n"
    "#   9  = Cycling Sensor (Appearance 0x0484, Service 0x1816) - Bike/Speed icon\n"
    "#   10 = Digital Stylus / Pen (HID 0x03C6, Service 0x1812) - Pen icon\n"
    "#   11 = Barcode Scanner (HID 0x03C5, Service 0x1812) - Scanner icon\n"
    "#   12 = Auto-Distribute Showcase (Each virtual network gets a DIFFERENT accessory icon!)\n"
    "accessory_type = 12\n"
    "\n"
    "# Custom Bluetooth device names (one per line, up to 16 names).\n"
    "# If left commented out or empty, it automatically matches the [networks] above!\n"
    "# IoT-Sensors-BLE\n"
    "# IoT-Cameras-BLE\n"
    "# IoT-Automation-BLE\n"
    "# IoT-Isolated-BLE\n"
    "# IoT-Guest-BLE\n"
    "\n"
    "[led]\n"
    "# Enable onboard addressable RGB LED indicator on GPIO8 (1 = enabled, 0 = disabled)\n"
    "# Telemetry events: Idle heartbeat, beacon injection, client probe interrogation, BLE rotation\n"
    "enable_led = 1\n"
    "\n"
    "# Global LED brightness percentage (0 to 100, default: 5)\n"
    "# Note: Bare WS2812 diodes without diffusers are piercingly bright!\n"
    "#   0   = Completely OFF\n"
    "#   1-5 = Gentle, soft indicator (recommended for desk use)\n"
    "#   10  = Moderate\n"
    "#   >20 = Bright / room lighting\n"
    "brightness = 5\n";
